# Generated by Django 4.1.7 on 2024-08-21 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="parent_comment",
            new_name="parent_response",
        ),
    ]
